title: CodingIsFun
description: coding is fun
google_analytics: true
show_downloads: false
theme: jekyll-theme-architect

gems:
  - jekyll-mentions

#defaults:
#  -
#    scope:
#      path: "" # for all files in projects
#    values:
#      layout: "default"
