title: CodingIsFun
description: coding is fun
google_analytics: 
show_downloads: true
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions

defaults:
  -
    scope:
      path: "" # for all files in projects
    values:
      layout: "default"
